version: '3.8'

networks:
  blogfrontend:
  blogbackend:

volumes:
  blogdata:

services:
  blogmysql:
    restart: always
    image: "mysql:latest"
    ports:
      - 3307:3306
    volumes:
      - blogdata:/var/lib/mysql
    networks:
      - blogbackend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      BIND-ADDRESS: 0.0.0.0
    command:
      --lower_case_table_names=1

  blogweb:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - blogbackend
      - blogfrontend
    environment:
      DBNAME: appsoft
      DBHOST: blogmysql
      DBPORT: 3306
      DBPWD: 123456
    depends_on:
      - blogmysql

  balance:
    restart: always
    image: dockercloud/haproxy:1.2.1
    ports:
      - 9000:80
    links:
      - blogweb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - blogfrontend