version: '3.7'

services:
  db:
    image: "mysql:8.0.0"
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: bind
        source: ${DB_VOLUME_SOURCE}
        target: /var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      BIND-ADDRESS: 0.0.0.0
    command:
      --lower_case_table_names=1

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ${WEB_VOLUME_APPSETTINGS_SOURCE}
        target: /app/appsettings.json
      - type: bind
        source: ${WEB_VOLUME_LOGS_SOURCE}
        target: /app/Logs
    networks:
      - backend
    environment:
      DBNAME: appsoft
      DBHOST: db
      DBPORT: 3306
      DBPWD: ${DB_PASSWORD}
    depends_on:
      - db
networks:
  backend:
