version: '3.7'

services:
  mysql:
    image: "mysql:8.0.0"
    ports:
      - 3316:3306
    volumes:
      - blogdata:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      BIND-ADDRESS: 0.0.0.0
    command:
      --lower_case_table_names=1

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    environment:
      DBNAME: appsoft
      DBHOST: mysql
      DBPORT: 3306
      DBPWD: 123456
    depends_on:
      - mysql

  balance:
    image: dockercloud/haproxy:1.2.1
    ports:
      - 9999:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  blogdata: